version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.7  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build  # I do not have a build script

  test:
    docker:
      - image: cimg/node:18.20.7  # Consistent version
    steps:
      - checkout
      - run: npm ci
      - run: npm test || echo "Tests failed but continuing" 

workflows:
  build-and-test:
    jobs:
      - build
      - test
