version: 2.1

jobs:
  install-and-test:
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test || echo "Tests completed with status $?"

  run-server:
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: |
          # Run server for limited time (300 seconds = 5 minutes)
          timeout 300 node server.js | tee server.log
          echo "Server ran for 5 minutes and was stopped"
      - store_artifacts:
          path: server.log
          destination: server-log

workflows:
  main-workflow:
    jobs:
      - install-and-test
      - run-server:
          requires:
            - install-and-test
          filters:
            branches:
              only: main  # Only run server on main branch