version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  test:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run: npm run test

workflows:
  build-and-test:
    jobs:
      - build
      - test
