version: 2.1

workflows:
  build-and-test:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "Building the app"
  
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "Running tests"